# .sops.yaml

keys:
  - &primary age1wqjp8qmdhqphz94mlawlvpz6eftecagt3tzuez7l5sznd7gqhsxqavga0x
  - &malenia age14qlrhplju9mvp8qg7fga8nu07r0grn9fw8f8mq3qs3wcxxjsayzshc56kk
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
        - *primary
        - *malenia
