[bar.default]
background_opacity = 0.84999999999999998
end = [ "notifications", "tray", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false
start = [ "control-center", "launcher", "workspaces", "media" ]

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
enabled = true
icon_size = 32
launcher_position = "start"
reserve_space = false

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 854.0
    cy = 841.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 841.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 474.0
    cy = 948.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
enabled = true

[plugins]
enabled = []

[shell]
avatar_path = "/home/tw1zzler/.face"
font_family = "Overpass Nerd Font"
niri_overview_type_to_launch_enabled = true

    [shell.animation]
    speed = 2.0

    [shell.launcher]
    session_search = true

    [shell.screenshot]
    confirm_region = true
    directory = "/home/tw1zzler/media/img/screenshots/desktop"
    filename_pattern = "%Y-%m-%d %H-%M-%S"

[theme]
builtin = "Catppuccin"
community_palette = "Everforest"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/tw1zzler/media/img/wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/tw1zzler/media/img/wallpapers/wallhaven_x8eyzl.jpg"

    [wallpaper.last]
    path = "/home/tw1zzler/media/img/wallpapers/wallhaven_x8eyzl.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/tw1zzler/media/img/wallpapers/wallhaven_x8eyzl.jpg"

[weather]
unit = "imperial"

[widget.battery]
capsule = true
capsule_radius = 4

[widget.bluetooth]
capsule = true
capsule_radius = 4

[widget.brightness]
capsule = true
capsule_radius = 4

[widget.clipboard]
capsule = true
capsule_radius = 4

[widget.clock]
capsule = true
capsule_radius = 4
format = " {:%Y-%m-%d} | {:%I:%M %p}"

[widget.control-center]
capsule = true
capsule_radius = 4

[widget.launcher]
capsule = true
capsule_radius = 4
glyph = "grid-dots"

[widget.media]
capsule = true
capsule_radius = 4
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
capsule = true
capsule_radius = 4
show_label = false

[widget.notifications]
capsule = true
capsule_radius = 4
hide_when_no_unread = true

[widget.session]
capsule = true
capsule_radius = 4

[widget.tray]
capsule = true
capsule_radius = 4

[widget.volume]
capsule = true
capsule_radius = 4

[widget.wallpaper]
capsule = true
capsule_radius = 4

[widget.workspaces]
capsule_radius = 4
empty_color = "primary"
focused_color = "tertiary"
hide_when_empty = true
occupied_color = "primary"
