# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d3b68968-2d97-4139-8ab7-78a82c6e78a9";
      fsType = "btrfs";
      options = [ "subvol=@nix-subsystem" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d3b68968-2d97-4139-8ab7-78a82c6e78a9";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/etc/NetworkManager/system-connections" =
    { device = "/nix/@/etc/NetworkManager/system-connections";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/tw1zzler" =
    { device = "/nix/@home/tw1zzler";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/tw1zzler/.cache" =
    { device = "/nix/@nix-subsystem/home/tw1zzler/.cache";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/tw1zzler/.config" =
    { device = "/nix/@nix-subsystem/home/tw1zzler/.config";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/tw1zzler/.local" =
    { device = "/nix/@nix-subsystem/home/tw1zzler/.local";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
